name: Asterios Katsifodimos
markdown: kramdown
highlighter: rouge

# URL settings for GitHub Pages
# For local dev: bundle exec jekyll serve --baseurl ""
url: "https://asterios.katsifodimos.com"
baseurl: ""
